#! python3


import cv2
# import time
import sys
import time
# from builtins import print
from Scripts import ImageProcessing as process
from Scripts import FrameExtraction as frame
from Scripts import GameControl as game
from Scripts.DirectKeys import ReleaseKey, PressKey, W, A, S, D

"""
image = cv2.imread("./Images/lena.jpg")
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Over the Clouds", image)
cv2.imshow("Over the Clouds - gray", gray_image)
# time.sleep(7)
cv2.waitKey(0)
cv2.destroyAllWindows()
"""

SCREEN_COOR_DIM = (10, 40, 800, 600)


def main():
    print(sys.version)
    last_time = time.time()

    game.WaitLoop()
    PressKey(W)
    # game.WaitLoop()
    # ReleaseKey(W)

    while True:
        printScreen_numpy = frame.getFrameFromSquare(SCREEN_COOR_DIM)
        # colorCorrectedImage = cv2.cvtColor(printScreen_numpy, cv2.COLOR_BGR2RGB)
        canny_edges = process.ExtractCannyEdges(printScreen_numpy)
        print('Loop took: {} seconds'.format(time.time() - last_time))  # Debug info
        last_time = time.time()

        cv2.imshow('window', canny_edges)
        if cv2.waitKey(25) & 0xFF == ord('q'):
            cv2.destroyAllWindows()
            break


main()
